### ISSUE TITLE
Broken Scannet Data Link and How to generate depth maps for new dataset 

### ISSUE THREAD

**Issue by georgeNakayama** [KU-CVLAB/DaRF#5]
Hi, thanks for the code release for this amazing work! I'm trying to reproduce the result from the paper on Scannet and it seems that the link to download the data is broken. 

I also want to test the model on a new dataset. I wonder how can I generate the Midase depth maps for the training images. I think the training of DaRF requires them. 

Thanks for the help!

**Comment by seong0905** [comment]
Hi, thank you for your interest in our research.

The link for downloading ScanNet has been updated, and it is now available.

We followed the [DPT](https://github.com/isl-org/DPT/tree/main) repository to generate MiDas depth maps. However, it is essential to set the 'invert' option of the DPTDepthModel to "True" to create the depth map.
By referring to our [DPT model code](https://github.com/KU-CVLAB/DaRF/blob/952c16d792d51c20b404a861291da196e741aba5/plenoxels/models/dpt_depth.py#L87
) and the section responsible for [forwarding the depth model](https://github.com/KU-CVLAB/DaRF/blob/952c16d792d51c20b404a861291da196e741aba5/plenoxels/runners/base_trainer.py#L235), you should be able to generate depth maps using the DPT model.
